[package]
name = "snowflake-api"
version = "0.3.2"
edition = "2021"
description = "Snowflake API bindings"
authors = ["Andrew Korzhuev <korzhuev@andrusha.me>"]
repository = "https://github.com/mycelial/snowflake-rs"
documentation = "http://docs.rs/sqlite-api/"
keywords = ["snowflake", "database", "api"]
categories = ["database", "api-bindings"]
readme = "README.md"
license = "Apache-2.0"

[dependencies]
thiserror = "1"
snowflake-jwt = "0.3.0"
reqwest = { version = "0.11", default-features = false, features = ["gzip", "rustls-tls", "json"] }
reqwest-middleware = "0.2"
reqwest-retry = "0.3"
log = "0.4"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
url = "2"
uuid = { version = "1", features = ["v4"] }
arrow = "47"
base64 = "0.21"
regex = "1"
object_store = { version = "0.7", features = ["aws"] }
async-trait = "0.1"
bytes = "1"
futures = "0.3"

[dev-dependencies]
anyhow = "1"
pretty_env_logger = "0.5"
clap = { version = "4", features = ["derive"] }
arrow = { version = "48", features = ["prettyprint"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
